const SUPABASE_URL="https://wtasyklliiwokxhvrhsq.supabase.co",SUPABASE_KEY="sb_publishable_-DHeEV3iTSOp-Vha03M5RA_MVUUk-s5";
const sb=supabase.createClient(SUPABASE_URL,SUPABASE_KEY),$=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const LOGIN="tattooizabella",ADMIN_EMAIL="admin@tattooizabella.studio";let settings={};
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(text){const e=$("#toast");e.textContent=text;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2600)}
function showPanel(){$("#login").classList.add("hidden");$("#panel").classList.remove("hidden");loadAll()}
async function loadAll(){await Promise.all([loadServices(),loadPortfolio(),loadSettings(),loadBookings()])}
$("#loginForm").onsubmit=async e=>{e.preventDefault();$("#loginError").textContent="";if($("#username").value.trim().toLowerCase()!==LOGIN){$("#loginError").textContent="Неверный логин или пароль";return}const{error}=await sb.auth.signInWithPassword({email:ADMIN_EMAIL,password:$("#password").value});if(error){$("#loginError").textContent="Неверный логин или пароль";return}showPanel()};
$("#logout").onclick=async()=>{await sb.auth.signOut();location.reload()};
$$('aside nav button').forEach(b=>b.onclick=()=>{$$('aside nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(v=>v.classList.remove('active'));$('#'+b.dataset.tab).classList.add('active');$('#pageTitle').textContent=b.querySelector('span').textContent;if(b.dataset.tab==='bookings')loadBookings()});
async function loadServices(){const{data=[],error}=await sb.from('services').select('*').order('position');if(error){toast('Ошибка загрузки услуг');return}$('#servicesCount').textContent=data.length;$('#servicesList').innerHTML=data.map(s=>`<article class="service-row"><div><h4>${esc(s.title_ru)}</h4><small>${esc(s.title_hy||s.title_en||'')}</small></div><strong>от ${Number(s.price_from).toLocaleString('ru-RU')} ֏</strong><div class="row-actions"><button data-edit-service='${JSON.stringify(s).replaceAll("'","&#39;")}'>Изменить</button><button class="danger" data-delete-service="${s.id}">Удалить</button></div></article>`).join('');$$('[data-edit-service]').forEach(b=>b.onclick=()=>openService(JSON.parse(b.dataset.editService)));$$('[data-delete-service]').forEach(b=>b.onclick=()=>deleteService(b.dataset.deleteService))}
function openService(s={}){const f=$('#serviceForm');f.reset();['id','title_ru','title_hy','title_en','price_from'].forEach(k=>f.elements[k].value=s[k]??'');$('#serviceDialog').showModal()}
$('#addService').onclick=()=>openService();$('#serviceForm').onsubmit=async e=>{e.preventDefault();const f=e.target,d={title_ru:f.title_ru.value,title_hy:f.title_hy.value||f.title_ru.value,title_en:f.title_en.value||f.title_ru.value,price_from:Number(f.price_from.value)};const{error}=f.id.value?await sb.from('services').update(d).eq('id',f.id.value):await sb.from('services').insert(d);if(error){toast('Не удалось сохранить');return}$('#serviceDialog').close();toast('Услуга сохранена');loadServices()};
async function deleteService(id){if(!confirm('Удалить эту услугу?'))return;const{error}=await sb.from('services').delete().eq('id',id);if(error){toast('Не удалось удалить');return}toast('Услуга удалена');loadServices()}
async function loadPortfolio(){const{data=[],error}=await sb.from('portfolio').select('*').order('position');if(error){toast('Ошибка загрузки галереи');return}$('#portfolioCount').textContent=data.length;$('#emptyPortfolio').style.display=data.length?'none':'block';$('#portfolioGrid').innerHTML=data.map(w=>`<article class="work-card"><button class="delete" data-delete="${w.id}" data-path="${esc(w.storage_path||w.instagram_url||'')}">×</button><img src="${esc(w.image_url)}" alt=""><div class="work-info"><b>${esc(w.title||'Без названия')}</b><span>${esc(w.category||'')}</span></div></article>`).join('');$$('[data-delete]').forEach(b=>b.onclick=()=>deleteWork(b.dataset.delete,b.dataset.path))}
async function timed(label,request,ms=45000){let timer;try{return await Promise.race([request,new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error(`${label}: превышено время ожидания`)),ms)})])}finally{clearTimeout(timer)}}
$('#addWork').onclick=()=>{$('#uploadStatus').textContent='';$('#uploadStatus').className='upload-status';$('#workDialog').showModal()};$('#workForm').onsubmit=async e=>{e.preventDefault();const f=e.target,files=[...f.image.files],submit=f.querySelector('[type="submit"]'),status=$('#uploadStatus');if(!files.length){status.textContent='Сначала выберите фотографии';status.className='upload-status error';return}submit.disabled=true;status.className='upload-status working';status.textContent=`Подготовка: ${files.length} фото…`;let added=0;const failed=[];try{const positionResult=await timed('Не удалось получить позицию',sb.from('portfolio').select('position').order('position',{ascending:false}).limit(1),15000);if(positionResult.error)throw positionResult.error;const last=Array.isArray(positionResult.data)?positionResult.data:[];let nextPosition=Number(last[0]?.position||0)+1;for(let i=0;i<files.length;i++){const file=files[i],path=`works/${Date.now()}-${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'-')}`;status.textContent=`Загрузка файла ${i+1} из ${files.length}: ${file.name}`;try{const up=await timed('Загрузка файла',sb.storage.from('portfolio').upload(path,file,{cacheControl:'3600',upsert:false}));if(up.error)throw up.error;const{data:url}=sb.storage.from('portfolio').getPublicUrl(path);if(!url?.publicUrl)throw new Error('Не получена ссылка на фотографию');status.textContent=`Сохранение в галерее: ${file.name}`;const saved=await timed('Сохранение в базе',sb.from('portfolio').insert({title:f.title.value||file.name.replace(/\.[^.]+$/,''),category:f.category.value,image_url:url.publicUrl,instagram_url:path,is_visible:true,position:nextPosition++}).select('id').single());if(saved.error){await sb.storage.from('portfolio').remove([path]);throw saved.error}added++}catch(error){failed.push(`${file.name}: ${error.message||'неизвестная ошибка'}`)}}if(!added)throw new Error(failed.join(' | ')||'Фотографии не добавлены');status.className='upload-status success';status.textContent=failed.length?`Добавлено: ${added}. Ошибок: ${failed.length}`:`Готово! Добавлено фотографий: ${added}`;await loadPortfolio();f.reset();toast(`Галерея обновлена: +${added}`);$('#workDialog').close()}catch(error){console.error('Gallery upload failed',error);status.className='upload-status error';status.textContent=`Ошибка: ${error.message||'не удалось загрузить фотографию'}`;toast('Фотография не добавлена')}finally{submit.disabled=false}};
async function deleteWork(id,path){if(!confirm('Удалить эту фотографию?'))return;if(path)await sb.storage.from('portfolio').remove([path]);const{error}=await sb.from('portfolio').delete().eq('id',id);if(error){toast('Не удалось удалить');return}toast('Фотография удалена');loadPortfolio()}
async function loadSettings(){const{data=[]}=await sb.from('site_settings').select('*');settings=Object.fromEntries(data.map(x=>[x.key,x.value]));const brand=settings.brand_name||'TATTOOIZABELLA',logo=settings.logo_url||'logo.jpg';$('[name="brand_name"]').value=brand;$('[name="artist_name"]').value=settings.artist_name||'Тигран Хачатрян';$('[name="booking_email"]').value=settings.booking_email||'tattooizabella@bk.ru';$('[name="hero_line_1"]').value=settings.hero_line_1||'ТВОЯ ИСТОРИЯ.';$('[name="hero_line_2"]').value=settings.hero_line_2||'ТВОЯ КОЖА.';$('[name="hero_line_3"]').value=settings.hero_line_3||'ТВОЁ ИСКУССТВО.';$('#logoPreview').src=logo;$$('[data-admin-logo]').forEach(x=>x.src=logo);$$('[data-admin-brand]').forEach(x=>x.textContent=brand)}
$('#settingsForm').onsubmit=async e=>{e.preventDefault();const f=e.target;let logoUrl=settings.logo_url||'logo.jpg';if(f.logo.files[0]){const file=f.logo.files[0],path=`branding/logo-${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'-')}`;const up=await sb.storage.from('portfolio').upload(path,file);if(up.error){toast('Не удалось загрузить логотип');return}logoUrl=sb.storage.from('portfolio').getPublicUrl(path).data.publicUrl}const values={brand_name:f.brand_name.value,artist_name:f.artist_name.value,hero_line_1:f.hero_line_1.value,hero_line_2:f.hero_line_2.value,hero_line_3:f.hero_line_3.value,logo_url:logoUrl};const rows=Object.entries(values).map(([key,value])=>({key,value}));const{error}=await sb.from('site_settings').upsert(rows,{onConflict:'key'});if(error){toast('Не удалось сохранить настройки');return}toast('Сайт обновлён');loadSettings()};
$('#emailForm').onsubmit=async e=>{e.preventDefault();const email=e.target.booking_email.value.trim();const{error}=await sb.from('site_settings').upsert({key:'booking_email',value:email},{onConflict:'key'});if(error){toast('Не удалось сохранить email: '+error.message);return}settings.booking_email=email;toast('Email для заявок сохранён')};
async function loadBookings(){const{data=[],error}=await sb.from('bookings').select('*').order('created_at',{ascending:false});if(error){toast('Ошибка загрузки заявок');return}for(const x of data){if(x.storage_path){const{data:signed}=await sb.storage.from('booking-files').createSignedUrl(x.storage_path,3600);x.attachment_url=signed?.signedUrl||''}}const fresh=data.filter(x=>x.status==='new').length;$('#bookingsCount').textContent=fresh;$('#newBadge').textContent=fresh||'';$('#emptyBookings').style.display=data.length?'none':'block';$('#bookingsList').innerHTML=data.map(x=>`<article class="booking ${x.status==='new'?'is-new':''}"><div><time>${new Date(x.created_at).toLocaleString('ru-RU')}</time><h4>${esc(x.name)}</h4><a href="tel:${esc(x.phone)}">${esc(x.phone)}</a><p>${esc(x.idea||'Без описания')}</p>${x.attachment_url?`<a class="attachment" href="${esc(x.attachment_url)}" target="_blank">Открыть файл: ${esc(x.attachment_name||'вложение')} ↗</a>`:''}</div><div class="booking-actions"><a class="secondary" href="https://wa.me/${esc(x.phone).replace(/\D/g,'')}" target="_blank">WhatsApp</a><button data-done="${x.id}">${x.status==='new'?'Отметить обработанной':'Обработано ✓'}</button><button class="danger" data-delete-booking="${x.id}">Удалить</button></div></article>`).join('');$$('[data-done]').forEach(b=>b.onclick=()=>markBooking(b.dataset.done));$$('[data-delete-booking]').forEach(b=>b.onclick=()=>deleteBooking(b.dataset.deleteBooking))}
async function markBooking(id){await sb.from('bookings').update({status:'done'}).eq('id',id);loadBookings()}
async function deleteBooking(id){if(!confirm('Удалить эту заявку?'))return;await sb.from('bookings').delete().eq('id',id);loadBookings()}
$('#refreshBookings').onclick=loadBookings;$$('dialog .close').forEach(b=>b.onclick=()=>b.closest('dialog').close());sb.auth.getSession().then(({data})=>{if(data.session)showPanel()});
