const SUPABASE_URL="https://wtasyklliiwokxhvrhsq.supabase.co";
const SUPABASE_KEY="sb_publishable_-DHeEV3iTSOp-Vha03M5RA_MVUUk-s5";
const sb=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const LOGIN="tattooizabella",ADMIN_EMAIL="admin@tattooizabella.studio";
function toast(text){const e=$("#toast");e.textContent=text;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2400)}
function showPanel(){ $("#login").classList.add("hidden");$("#panel").classList.remove("hidden");loadAll() }
async function loadAll(){await Promise.all([loadServices(),loadPortfolio()])}
$("#loginForm").onsubmit=async e=>{e.preventDefault();$("#loginError").textContent="";const username=$("#username").value.trim().toLowerCase();if(username!==LOGIN){$("#loginError").textContent="Неверный логин или пароль";return}const{error}=await sb.auth.signInWithPassword({email:ADMIN_EMAIL,password:$("#password").value});if(error){$("#loginError").textContent="Неверный логин или пароль";return}showPanel()};
$("#logout").onclick=async()=>{await sb.auth.signOut();location.reload()};
$$('aside nav button').forEach(b=>b.onclick=()=>{$$('aside nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(v=>v.classList.remove('active'));$('#'+b.dataset.tab).classList.add('active');$('#pageTitle').textContent=b.querySelector('span').textContent});
async function loadServices(){const{data,error}=await sb.from('services').select('*').order('position');if(error){toast('Ошибка загрузки услуг');return}$('#servicesCount').textContent=data.length;$('#servicesList').innerHTML=data.map(s=>`<article class="service-row"><div><h4>${esc(s.title_ru)}</h4><small>${esc(s.title_hy||s.title_en||'')}</small></div><strong>от ${Number(s.price_from).toLocaleString('ru-RU')} ֏</strong><button data-edit-service='${JSON.stringify(s).replaceAll("'","&#39;")}'>Изменить</button></article>`).join('');$$('[data-edit-service]').forEach(b=>b.onclick=()=>openService(JSON.parse(b.dataset.editService)))}
function openService(s={}){const f=$('#serviceForm');f.reset();['id','title_ru','title_hy','title_en','price_from'].forEach(k=>f.elements[k].value=s[k]??'');$('#serviceDialog').showModal()}
$('#addService').onclick=()=>openService();$('#serviceForm').onsubmit=async e=>{e.preventDefault();const f=e.target,d={title_ru:f.title_ru.value,title_hy:f.title_hy.value,title_en:f.title_en.value,price_from:Number(f.price_from.value)};const id=f.id.value;const q=id?sb.from('services').update(d).eq('id',id):sb.from('services').insert(d);const{error}=await q;if(error){toast('Не удалось сохранить');return}$('#serviceDialog').close();toast('Услуга сохранена');loadServices()};
async function loadPortfolio(){const{data,error}=await sb.from('portfolio').select('*').order('position');if(error){toast('Ошибка загрузки галереи');return}$('#portfolioCount').textContent=data.length;$('#emptyPortfolio').style.display=data.length?'none':'block';$('#portfolioGrid').innerHTML=data.map(w=>`<article class="work-card"><button class="delete" data-delete="${w.id}" data-path="${esc(w.storage_path||'')}">×</button><img src="${esc(w.image_url)}" alt=""><div class="work-info"><b>${esc(w.title||'Без названия')}</b><span>${esc(w.category||'')}</span></div></article>`).join('');$$('[data-delete]').forEach(b=>b.onclick=()=>deleteWork(b.dataset.delete,b.dataset.path))}
$('#addWork').onclick=()=>$('#workDialog').showModal();$('#workForm').onsubmit=async e=>{e.preventDefault();const f=e.target,file=f.image.files[0],path=`${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'-')}`;toast('Загрузка фотографии…');const up=await sb.storage.from('portfolio').upload(path,file);if(up.error){toast('Ошибка загрузки');return}const{data:url}=sb.storage.from('portfolio').getPublicUrl(path);const{error}=await sb.from('portfolio').insert({title:f.title.value,category:f.category.value,image_url:url.publicUrl,instagram_url:f.instagram_url.value,storage_path:path});if(error){toast('Ошибка сохранения');return}f.reset();$('#workDialog').close();toast('Работа добавлена');loadPortfolio()};
async function deleteWork(id,path){if(!confirm('Удалить эту работу из галереи?'))return;if(path)await sb.storage.from('portfolio').remove([path]);await sb.from('portfolio').delete().eq('id',id);toast('Работа удалена');loadPortfolio()}
$$('dialog .close').forEach(b=>b.onclick=()=>b.closest('dialog').close());function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
sb.auth.getSession().then(({data})=>{if(data.session)showPanel()});
